organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - cynthia-sg
    members:
      - Clomonitor1
  - name: team2
    maintainers:
      - cynthia-sg
    members:
      - tegioz
repositories:
  - name: .clowarden
    teams:
      team1: admin
    external_collaborators:
      tegioz: admin
    visibility: private
  - name: tests
    external-collaborators:
      cynthia-sg: write
      tegioz: admin
    visibility: private
  - name: tests-2
    external-collaborators:
      cynthia-sg: admin
      tegioz: read
    visibility: private
