organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - cynthia-sg
    members:
      - Clomonitor1
repositories:
  - name: .clowarden
    teams:
      team1: admin
    external_collaborators:
      tegioz: admin
    visibility: private
